version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s %(levelname)s [%(process)d:%(threadName)s] %(name)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

root:
  level: DEBUG
  handlers: [console]
